### ISSUE TITLE
New Builds

### ISSUE THREAD

**Issue by yo1dog** [cjw1115/enable-chromium-ac3-ec3-system-decoding#2]
The releases page states that builds are synced with https://github.com/StaZhu/enable-chromium-hevc-hardware-decoding, but now that hevc is included in public prod builds, can we get a new build?

Thanks!
 - Mike

**Comment by StaZhu** [comment]
You can actually just use the binary in that repo, It has integrated both HEVC and AC3/E-AC3 support since M115.

**Comment by cjw1115** [comment]
As @StaZhu's comment, you can use build in his HEVC repo.
